ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
path('addtocart/<str:n>/',views.addtocart,name='addtocart'),
    path('cartview/',views.cartview,name='cartview'),
    path('remove/<str:n>/',views.remove,name='remove'),
    path('delete/<str:n>/',views.delete,name='delete'),
    path('orderform', views.orderform, name='order_form')
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from shop import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from search import views
app_name='search'
urlpatterns = [
path('',views.search,name='search')
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allcategories,name='category'),
    path('allproducts/<p>',views.allproducts,name='allproducts'),
    path('productdetails/<p>',views.productdetails,name='details'),
    path('login', views.user_login, name="login"),
    path('register', views.register, name="register"),
    path('logout', views.user_logout, name="logout"),




]

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Products
# Create your models here.

class Cart(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    ordered_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField()
    order_satatus=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    def __str__(self):
        return self.user.product.name


class Account(models.Model):
    acctnum=models.IntegerField()
    acctype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/category",null=True,blank=True)

    def __str__(self):
        return self.name

class Products(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField()
    image = models.ImageField(upload_to="images/products", null=True, blank=True)
    price= models.IntegerField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from cart.models import Cart
from shop.models import Products
# Create your views here.
def addtocart(request,n):
    p=Products.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
            cart.save()
    except:
        if(p.stock > 0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
    return cartview(request)


def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total=i.quantity*i.product.price
    return render(request,'cartview.html',{'c':cart,'total':total})


def remove(request,n):
    p = Products.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()
    except:
        pass
    return cartview(request)

def delete(request,n):
    p = Products.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity ):
            cart.delete()
        else:
            cart.delete()
    except:
        pass

    return cartview(request)
def orderform(request):
    return render(request,'orderform.html')

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Products
from django.db.models import Q
# Create your views here.

def search(request):
    query = ""
    products = None
    if request.method == "POST":
        query = request.POST.get('q', '')
        if query:
            products = Products.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request, "search.html", {'query': query, 'p': products})

ecommerce/shop/views.py
from django.shortcuts import render
from shop.models import Category
from shop.models import Products
# Create your views here.
def allcategories(request):
    c = Category.objects.all()
    return render(request, 'category.html', {'c': c})


def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Products.objects.filter(category=c)
    return render(request,'products.html',{'c':c , 'p':p})

def productdetails(request,p):
    p= Products.objects.get(name=p)
    return render(request, 'productdetails.html', {'p': p})




from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect



# Create your views here.
def user_login(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        user = authenticate(username = u , password = p)
        if user:
            login(request,user)
            return redirect('shop:category')
        else:
            return HttpResponse("Invalid")

    return render(request, "login.html")
def user_logout(request):
    logout(request)
    return redirect('shop:login')

def register(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        fn = request.POST['fn']
        ln = request.POST['ln']
        e = request.POST['e']

        if (p == cp):
            user = User.objects.create_user(username=u, password=p, first_name=fn, last_name=ln, email=e )
            user.save()
            return redirect('shop:category')
        else:
            return HttpResponse("Passwords are not same")
    return render(request, "register.html")

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Ashpuverse</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <div class="container-fluid">
            <center> <img src="{% static 'images/logo.png' %}" height="100px" width="100px" ></center>
        </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FAF9F6 ;">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" width="50" height="50" alt="">
        </a>
        <a class="navbar-brand" href="{% url 'shop:category' %}">ASHPUVERSE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:category' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for i in links %}
                        <a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{ i.name }}</a>
                       {% endfor %}
                    </div>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:logout' %}">Logout <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sub>{{count}}</sub> <span class="sr-only">(current)</span></a>
                </li>
                {% else %}

                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:login' %}">Login <span class="sr-only"></span></a>
                </li>

               <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shop:register' %}">Register <span class="sr-only"></span></a>
                </li>
{% endif %}

            </ul>
            <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'search:search' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    {% block content %}


    {% endblock %}



    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <center><span class="text-muted">&copy; {{ today|date:"Y" }} Ashpuverse. All rights reserved.</span>
            </center>
        </div>

    </footer>


</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid">
    <h4 class="text-center"> Shopping Cart</h4>
  </div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
        <th scope="col"> Check out</th>
  <th>Total</th>

    </tr>
  </thead>
  <tbody>
  {% for i in c %}
    <tr>
      <td><img src="{{i.product.image.url}} " height="150px" width="150px"></td>
      <td>{{i.product.name}}</td>
      <td>Unit Price : {{i.product.price }}<br>
      Quantity : {{ i.quantity}}</td>
<td>Total price : {{i.subtotal}}</td>
      <td>
          {% if i.quantity < i.product.stock %}
          <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-cart-plus" style="color: #000000;"></i>
      </a> &nbsp;<a href="{% url 'cart:remove' i.product.name %}"><i class="fa-solid fa-cart-arrow-down" style="color: #000000;"></i></a>
        &nbsp;<a href="{% url 'cart:delete' i.product.name %}"><i class="fa-solid fa-trash-can" style="color: #000000;"></i></a> </td>
      <td>Total:{{total}}</td>
        {% else %}
        <td>&nbsp;<a href="{% url 'cart:remove' i.product.name %}"><i class="fa-solid fa-cart-arrow-down" style="color: #000000;"></i></a>
        &nbsp;<a href="{% url 'cart:delete' i.product.name %}"><i class="fa-solid fa-trash-can" style="color: #000000;"></i></a> </td>
        <td><button>Total:{{total}}</td>

  {% endif %}</td>  </tr>
  {% endfor %}
  </tbody>
</table>
<a href="{% url 'cart:order_form' %}" class="btn btn-dark" >Place order</a>
<a href="{% url 'shop:category' %}" class="btn btn-dark"  >Continue shopping</a>
{% endblock %}

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <img src="{% static 'images/banner.jpg' %}" height="450px" width="100%">
    <h3 class="text-center fw-bold"> OUR COLLECTION</h3>
    <P style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</P>
</div>
<div class="card-container d-flex flex-row mx-auto">
  {% for i in c %}
    <div class="card my-3"> <!-- Added "my-3" class for margin on the y-axis (top and bottom) -->
      <img src="{{ i.image.url }}" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{ i.name }}</h5>
        <p class="card-text"></p>
        <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary">Products</a>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Login</h3>
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="enter the username">
      </div>
       <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="enter password">
      </div>
        <input type="submit" class="form-control">
    </form>
</center>

{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock %}

ecommerce/templates/productdetails.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <div class="img-container">
                <img src="{{ p.image.url }}" class="img-fluid" alt="Product Image">
            </div>
            </div>
            <div class="col-md-6">

                <h2>{{p.name}}</h2>
                <p class="text-muted">{{p.desc}}</p>
                <p>Price: {{p.price}} </p>
                <a href="{% url 'cart:addtocart' p.name %}"  class="btn btn-lg" style="background-color: black; color: white;">Add to Cart</a>
            </div>
        </div>
    </div>

{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{{ c.image.url }}" height=" 450px" width="100%">

</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
<p style="text-align:justify; line-height:2";> {{ c.desc }}</p>
</div>
<div class="card-container d-flex flex-row">
  {% for i in p%}
    <div class="card">
      <img src="{{ i.image.url }}" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{ i.name }}</h5>
        <p class="card-text"></p>
        <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Details</a>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <form method="POST">
      {% csrf_token %}
      <h3 class="mt-4">Registration</h3>
      <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="enter the username">
      </div>
      <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="enter password">
      </div>
      <div class="mb-3">
        <label class="form-label">Confirm password</label>
        <input type="password" class="form-control" name="cp" placeholder="re-enter your password">
      </div>
        <div class="mb-3">
        <label class="form-label">First name</label>
        <input type="text" class="form-control" name="fn" placeholder="enter your first name">
      </div>
        <div class="mb-3">
        <label class="form-label">Last name</label>
        <input type="text" class="form-control" name="ln" placeholder="enter your last name">
      </div>
        <div class="mb-3">
        <label class="form-label">Email address</label>
        <input type="email" class="form-control" name="e" placeholder="enter your email address">
      </div>

      <input type="submit" class="form-control">
    </form>
</center>

{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
<center>
<h3 class="mt-4">You have searched for {{query}}</h3>
  <div class="card-container d-flex flex-row">
  {% for i in p%}
    <div class="card">
      <img src="{{ i.image.url }}" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">{{ i.name }}</h5>
        <p class="card-text"></p>
        <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Details</a>
      </div>
    </div>
  {% endfor %}
</div>
    {% endblock %}

ecommerce/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



{% endblock %}